-- Fix group hike live location sync
-- 1) Ensure team_members has fields used by frontend
ALTER TABLE public.team_members
  ADD COLUMN IF NOT EXISTS user_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS user_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS last_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS last_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_team_members_team_last_seen
  ON public.team_members(team_id, last_seen_at DESC);

-- 2) Normalize team_members policies to avoid uuid/text comparison issues
DROP POLICY IF EXISTS team_members_view ON public.team_members;
DROP FUNCTION IF EXISTS public.is_team_member(UUID);
CREATE FUNCTION public.is_team_member(team_uuid UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.team_members tm
    WHERE tm.team_id = team_uuid
      AND tm.user_id::text = auth.uid()::text
  );
$$;

REVOKE ALL ON FUNCTION public.is_team_member(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_team_member(UUID) TO authenticated, anon;

CREATE POLICY team_members_view ON public.team_members
  FOR SELECT USING (public.is_team_member(team_id));

DROP POLICY IF EXISTS team_members_insert ON public.team_members;
CREATE POLICY team_members_insert ON public.team_members
  FOR INSERT WITH CHECK (user_id::text = auth.uid()::text);

DROP POLICY IF EXISTS team_members_update_own ON public.team_members;
CREATE POLICY team_members_update_own ON public.team_members
  FOR UPDATE USING (user_id::text = auth.uid()::text)
  WITH CHECK (user_id::text = auth.uid()::text);

-- 3) Create locations history table used by CompanionView
CREATE TABLE IF NOT EXISTS public.locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT,
  team_id UUID REFERENCES public.teams(id) ON DELETE SET NULL,
  user_id TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT locations_lat_check CHECK (latitude BETWEEN -90 AND 90),
  CONSTRAINT locations_lng_check CHECK (longitude BETWEEN -180 AND 180)
);

-- If locations table already existed, backfill missing columns used by app/policies
ALTER TABLE public.locations
  ADD COLUMN IF NOT EXISTS session_id TEXT,
  ADD COLUMN IF NOT EXISTS team_id UUID,
  ADD COLUMN IF NOT EXISTS user_id TEXT,
  ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'locations_team_id_fkey'
      AND conrelid = 'public.locations'::regclass
  ) THEN
    ALTER TABLE public.locations
      ADD CONSTRAINT locations_team_id_fkey
      FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE SET NULL;
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_locations_team_created_at
  ON public.locations(team_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_locations_session_created_at
  ON public.locations(session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_locations_user_created_at
  ON public.locations(user_id, created_at DESC);

ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS locations_insert_own ON public.locations;
CREATE POLICY locations_insert_own ON public.locations
  FOR INSERT WITH CHECK (user_id::text = auth.uid()::text);

DROP POLICY IF EXISTS locations_select_own_or_team ON public.locations;
CREATE POLICY locations_select_own_or_team ON public.locations
  FOR SELECT USING (
    user_id::text = auth.uid()::text
    OR (
      team_id IS NOT NULL
      AND EXISTS (
        SELECT 1
        FROM public.team_members tm
        WHERE tm.team_id = locations.team_id
          AND tm.user_id::text = auth.uid()::text
      )
    )
  );

-- 4) Ensure realtime publication includes team_members and locations
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'team_members'
    ) THEN
      EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.team_members';
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'locations'
    ) THEN
      EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.locations';
    END IF;
  END IF;
END
$$;
