-- 0. Ensure hike_sessions table exists
CREATE TABLE IF NOT EXISTS public.hike_sessions (
    id TEXT PRIMARY KEY, -- Use the session_ string generated in App.tsx
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    team_id UUID REFERENCES public.teams(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 1. Create user_saved_routes table
-- Used to save AI-generated routes (compositions of segments) for later use
CREATE TABLE IF NOT EXISTS public.user_saved_routes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    segment_ids UUID[] NOT NULL, -- Array of route_segments IDs
    total_distance DECIMAL(10,2),
    total_duration_minutes INTEGER,
    total_elevation_gain INTEGER,
    tags TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enhance hike_sessions to support better linking
-- Ensure sessions can be tied to a specific team and route
ALTER TABLE public.hike_sessions 
ADD COLUMN IF NOT EXISTS target_route_id UUID REFERENCES public.routes(id),
ADD COLUMN IF NOT EXISTS is_solo BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active'; -- active, completed, paused

-- 3. Create track_waypoints table (Optional but recommended for scalability)
-- Moving waypoints out of JSONB for better geospatial queries
CREATE TABLE IF NOT EXISTS public.track_waypoints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    track_id UUID REFERENCES public.user_tracks(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id),
    type TEXT NOT NULL, -- 'photo', 'marker'
    note TEXT,
    image_url TEXT,
    latitude DECIMAL(10,8) NOT NULL,
    longitude DECIMAL(11,8) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_saved_routes_user_id ON public.user_saved_routes(user_id);
CREATE INDEX IF NOT EXISTS idx_track_waypoints_track_id ON public.track_waypoints(track_id);

-- Enable RLS
ALTER TABLE public.user_saved_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.track_waypoints ENABLE ROW LEVEL SECURITY;

-- Simple RLS Policies
CREATE POLICY "Users can manage their own saved routes" 
ON public.user_saved_routes FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own waypoints" 
ON public.track_waypoints FOR ALL USING (auth.uid() = user_id);

COMMENT ON TABLE public.user_saved_routes IS 'Stores custom segment-based routes generated by AI or composed by users.';
COMMENT ON TABLE public.track_waypoints IS 'Stores individual markers and photos taken during a hike, extracted from track data.';
