-- Ensure team emotion notes support realtime sync across teammates

CREATE TABLE IF NOT EXISTS public.team_member_emotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id UUID REFERENCES public.teams(id) ON DELETE SET NULL,
  user_id TEXT NOT NULL,
  user_name VARCHAR(255),
  content TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT team_member_emotions_lat_check CHECK (latitude BETWEEN -90 AND 90),
  CONSTRAINT team_member_emotions_lng_check CHECK (longitude BETWEEN -180 AND 180)
);

ALTER TABLE public.team_member_emotions
  ADD COLUMN IF NOT EXISTS team_id UUID,
  ADD COLUMN IF NOT EXISTS user_id TEXT,
  ADD COLUMN IF NOT EXISTS user_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS content TEXT,
  ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'team_member_emotions_team_id_fkey'
      AND conrelid = 'public.team_member_emotions'::regclass
  ) THEN
    ALTER TABLE public.team_member_emotions
      ADD CONSTRAINT team_member_emotions_team_id_fkey
      FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE SET NULL;
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_team_member_emotions_team_created_at
  ON public.team_member_emotions(team_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_team_member_emotions_user_created_at
  ON public.team_member_emotions(user_id, created_at DESC);

ALTER TABLE public.team_member_emotions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS team_member_emotions_insert_own ON public.team_member_emotions;
CREATE POLICY team_member_emotions_insert_own ON public.team_member_emotions
  FOR INSERT WITH CHECK (user_id::text = auth.uid()::text);

DROP POLICY IF EXISTS team_member_emotions_select_own_or_team ON public.team_member_emotions;
CREATE POLICY team_member_emotions_select_own_or_team ON public.team_member_emotions
  FOR SELECT USING (
    user_id::text = auth.uid()::text
    OR (
      team_id IS NOT NULL
      AND EXISTS (
        SELECT 1
        FROM public.team_members tm
        WHERE tm.team_id = team_member_emotions.team_id
          AND tm.user_id::text = auth.uid()::text
      )
    )
  );

DROP POLICY IF EXISTS team_member_emotions_update_own ON public.team_member_emotions;
CREATE POLICY team_member_emotions_update_own ON public.team_member_emotions
  FOR UPDATE
  USING (user_id::text = auth.uid()::text)
  WITH CHECK (user_id::text = auth.uid()::text);

DROP POLICY IF EXISTS team_member_emotions_delete_own ON public.team_member_emotions;
CREATE POLICY team_member_emotions_delete_own ON public.team_member_emotions
  FOR DELETE USING (user_id::text = auth.uid()::text);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'team_member_emotions'
    ) THEN
      EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.team_member_emotions';
    END IF;
  END IF;
END
$$;
