// ============================================================================
// services/groupNegotiationService.ts
// AI 驱动的团队偏好综合分析和路由推荐
// ============================================================================

import { supabase } from './supabaseClient';
import { findMatchingRoutes, UserHikingPreferences } from './segmentRoutingService';
import { callGeminiAPI } from './geminiService';
import * as teamService from './teamService';

// ============================================================================
// 类型定义
// ============================================================================

export interface MemberPreference {
  userId: string;
  mood: string;
  difficulty: string;
  condition: string;
  availableTime: number;
  maxDistance: number;
}

export interface SynthesizedPreferences {
  synthesizedMood: string;
  synthesizedDifficulty: string;
  synthesizedCondition: string;
  analysis: string;
  considerations: string[];
}

export interface GroupNegotiationResult {
  teamId: string;
  memberCount: number;
  synthesizedPreferences: SynthesizedPreferences;
  recommendedRoutes: any[]; // RouteMatchScore[]
  autoGeneratedTitle: string;
  negotiationId: string;
}

// ============================================================================
// 主流程：Social Negotiation
// ============================================================================

/**
 * 执行团队的 "Social Negotiation" - AI 综合所有队员的偏好
 * @param teamId - 团队 ID
 * @param initiatorId - 启动者 ID（应该是队长）
 * @returns 综合分析结果和推荐路由
 */
export async function performGroupNegotiation(
  teamId: string,
  initiatorId: string
): Promise<GroupNegotiationResult> {
  console.log(`[Group Negotiation] Starting for team ${teamId}`);

  // 1. 验证队长身份
  const isLeader = await teamService.isTeamLeader(teamId, initiatorId);
  if (!isLeader) {
    throw new Error('Only team leader can initiate group negotiation');
  }

  // 2. 检查所有成员是否完成了偏好设置
  const allCompleted = await teamService.areAllPreferencesCompleted(teamId);
  if (!allCompleted) {
    throw new Error('Not all team members have completed their preferences');
  }

  // 3. 获取所有队员的偏好
  const memberPreferences = await teamService.getAllMemberPreferences(teamId);
  if (memberPreferences.length === 0) {
    throw new Error('No member preferences found');
  }

  console.log(`[Group Negotiation] Retrieved ${memberPreferences.length} member preferences`);

  // 4. 调用 AI 进行综合分析
  const synthesized = await synthesizePreferencesWithAI(memberPreferences);

  console.log('[Group Negotiation] AI analysis completed');
  console.log('Synthesized mood:', synthesized.synthesizedMood);
  console.log('Synthesized difficulty:', synthesized.synthesizedDifficulty);
  console.log('Synthesized condition:', synthesized.synthesizedCondition);

  // 5. 基于综合偏好进行路由匹配
  const recommendedRoutes = await findMatchingRoutes({
    mood: synthesized.synthesizedMood,
    difficulty: synthesized.synthesizedDifficulty,
    condition: synthesized.synthesizedCondition,
    availableTime: calculateAverageTime(memberPreferences),
    maxDistance: calculateAverageDistance(memberPreferences),
  });

  console.log(`[Group Negotiation] Found ${recommendedRoutes.length} recommended routes`);

  // 6. 自动生成分组标题
  const autoTitle = generateGroupTitle(synthesized.synthesizedMood, memberPreferences.length);

  // 7. 保存到数据库
  const negotiationId = await saveNegotiationHistory(
    teamId,
    initiatorId,
    memberPreferences,
    synthesized,
    recommendedRoutes
  );

  // 8. 更新团队的综合偏好
  await updateTeamSynthesizedPreferences(teamId, synthesized);

  return {
    teamId,
    memberCount: memberPreferences.length,
    synthesizedPreferences: synthesized,
    recommendedRoutes,
    autoGeneratedTitle: autoTitle,
    negotiationId,
  };
}

// ============================================================================
// AI 综合分析
// ============================================================================

/**
 * 使用 Gemini AI 综合所有队员的偏好
 * @param preferences - 所有队员的偏好数组
 * @returns 综合后的偏好和分析
 */
async function synthesizePreferencesWithAI(
  preferences: MemberPreference[]
): Promise<SynthesizedPreferences> {
  // 构建提示词
  const prompt = constructNegotiationPrompt(preferences);

  console.log('[AI Negotiation] Sending prompt to Gemini API');
  console.log('Prompt:', prompt);

  try {
    const response = await callGeminiAPI(prompt);

    // 解析 AI 响应
    const parsed = parseAIResponse(response);

    return parsed;
  } catch (error) {
    console.error('[AI Negotiation] Error calling Gemini API:', error);
    throw error;
  }
}

/**
 * 构建 AI 提示词 - 指导 AI 如何综合队员偏好
 */
function constructNegotiationPrompt(preferences: MemberPreference[]): string {
  const memberSummaries = preferences
    .map((p, idx) => {
      return `
Member ${idx + 1}:
- Mood/Style: ${p.mood}
- Difficulty Level: ${p.difficulty} (1-5 scale)
- Specific Requests: ${p.condition}
- Available Time: ${p.availableTime} minutes
- Maximum Distance: ${p.maxDistance} km
`;
    })
    .join('\n');

  const prompt = `You are an expert hiking tour guide and group coordinator. Your task is to synthesize the hiking preferences of a group and create a unified hiking plan that satisfies everyone.

Group Members' Preferences:
${memberSummaries}

Based on all members' preferences, please:

1. Analyze the group's combined interests and constraints
2. Identify common themes and potential compromises
3. Determine a synthesized hiking approach that balances all preferences
4. Provide the output in the following JSON format:

{
  "synthesizedMood": "[one of: Adventurous, Peaceful, Scenic, Social, Challenging, Family-friendly, or a combination]",
  "synthesizedDifficulty": "[easy, medium, or hard]",
  "synthesizedCondition": "[A 1-2 sentence description of the ideal hiking route for this group, considering all constraints]",
  "analysis": "[2-3 sentences explaining your recommendations and how they address the group's needs]",
  "considerations": [
    "[Important consideration 1]",
    "[Important consideration 2]",
    "[Important consideration 3]"
  ]
}

IMPORTANT:
- The synthesizedMood should reflect the group's overall character
- Difficulty should be achievable for all members (match the lowest requirement or one level above)
- The synthesizedCondition should be specific and actionable for route matching
- Ensure your analysis is balanced and considers all preferences equally
- Return ONLY valid JSON, no additional text`;

  return prompt;
}

/**
 * 解析 AI 返回的响应
 */
function parseAIResponse(response: string): SynthesizedPreferences {
  console.log('[AI Response] Parsing response');

  // 尝试提取 JSON
  const jsonMatch = response.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    console.error('[AI Response] No JSON found in response');
    throw new Error('AI response does not contain valid JSON');
  }

  const jsonStr = jsonMatch[0];
  console.log('[AI Response] Extracted JSON:', jsonStr);

  try {
    const parsed = JSON.parse(jsonStr);

    // 验证必需字段
    if (
      !parsed.synthesizedMood ||
      !parsed.synthesizedDifficulty ||
      !parsed.synthesizedCondition
    ) {
      throw new Error('Missing required fields in AI response');
    }

    return {
      synthesizedMood: parsed.synthesizedMood,
      synthesizedDifficulty: parsed.synthesizedDifficulty,
      synthesizedCondition: parsed.synthesizedCondition,
      analysis: parsed.analysis || '',
      considerations: parsed.considerations || [],
    };
  } catch (error) {
    console.error('[AI Response] JSON parse error:', error);
    throw error;
  }
}

// ============================================================================
// 计算辅助函数
// ============================================================================

/**
 * 计算队员的平均可用时间
 */
function calculateAverageTime(preferences: MemberPreference[]): number {
  if (preferences.length === 0) return 300;

  const times = preferences.map((p) => p.availableTime);
  const sum = times.reduce((a, b) => a + b, 0);

  // 返回最小时间和平均时间中较小的值（保守估计）
  const min = Math.min(...times);
  const avg = Math.round(sum / times.length);

  return Math.min(min, avg);
}

/**
 * 计算队员的平均最大距离（保守估计）
 */
function calculateAverageDistance(preferences: MemberPreference[]): number {
  if (preferences.length === 0) return 20;

  const distances = preferences.map((p) => p.maxDistance);

  // 返回最小距离（因为这是所有人都能接受的）
  return Math.min(...distances);
}

/**
 * 自动生成分组标题
 */
function generateGroupTitle(mood: string, memberCount: number): string {
  const moodTitles: Record<string, string> = {
    adventurous: 'Adventure Squad Challenge',
    peaceful: 'Serenity Seekers Hike',
    scenic: 'Scenic Explorers Route',
    social: 'Fellowship Trail',
    challenging: 'Peak Hunters Journey',
    'family-friendly': 'Family Adventure Day',
    mixed: 'Group Harmony Trail',
  };

  const baseMood = mood.toLowerCase().split(' ')[0];
  const baseTitle = moodTitles[baseMood] || 'Group Harmony Trail';

  return `${baseTitle} (${memberCount} members)`;
}

// ============================================================================
// 数据库操作
// ============================================================================

/**
 * 保存协商历史到数据库
 */
async function saveNegotiationHistory(
  teamId: string,
  initiatorId: string,
  memberPreferences: MemberPreference[],
  synthesized: SynthesizedPreferences,
  recommendedRoutes: any[]
): Promise<string> {
  const { data, error } = await supabase
    .from('team_negotiation_history')
    .insert({
      team_id: teamId,
      initiated_by: initiatorId,
      member_preferences: memberPreferences,
      member_count: memberPreferences.length,
      ai_analysis: synthesized.analysis,
      synthesized_mood: synthesized.synthesizedMood,
      synthesized_difficulty: synthesized.synthesizedDifficulty,
      synthesized_condition: synthesized.synthesizedCondition,
      recommended_routes: recommendedRoutes.map((r) => ({
        id: r.id,
        name: r.name,
        score: r.score,
        matchReasons: r.matchReasons,
      })),
    })
    .select('id')
    .single();

  if (error) {
    console.error('[DB] Error saving negotiation history:', error);
    throw error;
  }

  return data.id;
}

/**
 * 保存生成的路由和标题
 */
async function saveGeneratedRoutes(
  teamId: string,
  negotiationId: string,
  generatedBy: string,
  synthesized: SynthesizedPreferences,
  recommendedRoutes: any[],
  autoTitle: string
): Promise<string> {
  const { data, error } = await supabase
    .from('team_generated_routes')
    .insert({
      team_id: teamId,
      negotiation_id: negotiationId,
      generated_by: generatedBy,
      synthetic_query: synthesized.synthesizedCondition,
      routes: recommendedRoutes,
      auto_generated_title: autoTitle,
    })
    .select('id')
    .single();

  if (error) {
    console.error('[DB] Error saving generated routes:', error);
    throw error;
  }

  return data.id;
}

/**
 * 更新团队的综合偏好
 */
async function updateTeamSynthesizedPreferences(
  teamId: string,
  synthesized: SynthesizedPreferences
): Promise<void> {
  const { error } = await supabase
    .from('teams')
    .update({
      hiking_mood: synthesized.synthesizedMood,
      hiking_difficulty: synthesized.synthesizedDifficulty,
      hiking_preferences: {
        synthesized_condition: synthesized.synthesizedCondition,
        considerations: synthesized.considerations,
      },
      negotiation_completed: true,
      updated_at: new Date().toISOString(),
    })
    .eq('id', teamId);

  if (error) {
    console.error('[DB] Error updating team preferences:', error);
    throw error;
  }
}

/**
 * 选择推荐的路由
 */
export async function selectGroupRoute(
  teamId: string,
  routeId: string,
  negotiationId: string
): Promise<void> {
  const { error } = await supabase
    .from('team_negotiation_history')
    .update({
      selected_route_id: routeId,
    })
    .eq('id', negotiationId);

  if (error) {
    console.error('[DB] Error selecting route:', error);
    throw error;
  }

  // 更新团队状态
  await supabase
    .from('teams')
    .update({
      status: 'hiking',
      updated_at: new Date().toISOString(),
    })
    .eq('id', teamId);
}

/**
 * 获取团队的协商历史
 */
export async function getTeamNegotiationHistory(teamId: string): Promise<any[]> {
  const { data, error } = await supabase
    .from('team_negotiation_history')
    .select('*')
    .eq('team_id', teamId)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('[DB] Error fetching negotiation history:', error);
    throw error;
  }

  return data || [];
}

/**
 * 重新运行协商（如果有成员更改了偏好）
 */
export async function rerunNegotiation(
  teamId: string,
  initiatorId: string
): Promise<GroupNegotiationResult> {
  console.log('[Negotiation] Rerunning negotiation for team:', teamId);
  return performGroupNegotiation(teamId, initiatorId);
}

// ============================================================================
// 辅助函数
// ============================================================================

/**
 * 格式化队员偏好用于显示
 */
export function formatMemberPreferences(pref: MemberPreference): string {
  return `${pref.mood} • ${pref.difficulty.charAt(0).toUpperCase() + pref.difficulty.slice(1)} • "${pref.condition}"`;
}

/**
 * 获取难度文本描述
 */
export function getDifficultyDescription(difficulty: string): string {
  const descriptions: Record<string, string> = {
    easy: 'Suitable for all fitness levels, minimal elevation gain',
    medium: 'Moderate fitness required, some elevation and technical sections',
    hard: 'Good fitness needed, significant elevation and challenging terrain',
  };

  return descriptions[difficulty.toLowerCase()] || difficulty;
}

/**
 * 获取心情文本描述
 */
export function getMoodDescription(mood: string): string {
  const descriptions: Record<string, string> = {
    adventurous: 'Seeking challenges and new experiences',
    peaceful: 'Looking for relaxation and natural tranquility',
    scenic: 'Focused on beautiful views and photography',
    social: 'Emphasizing group bonding and interaction',
    challenging: 'Wanting to test physical limits',
    'family-friendly': 'Safe and enjoyable for all ages',
  };

  return descriptions[mood.toLowerCase()] || mood;
}

export default {
  performGroupNegotiation,
  selectGroupRoute,
  getTeamNegotiationHistory,
  rerunNegotiation,
  formatMemberPreferences,
  getDifficultyDescription,
  getMoodDescription,
};
